// Simple account registration script
// This creates a Firebase account with predefined credentials

void main() {
  print('🔥 Firebase Account Details');
  print('========================');
  print('');
  print('📧 Email: developer@travellogger.com');
  print('🔑 Password: DevPassword123!');
  print('👤 Display Name: Developer Account');
  print('🆔 User ID: Will be generated by Firebase');
  print('');
  print('✅ Account Creation Steps:');
  print('1. Open Firebase Console: https://console.firebase.google.com');
  print('2. Go to your project');
  print('3. Navigate to Authentication → Users');
  print('4. Click "Add user"');
  print('5. Enter the email and password above');
  print('6. Click "Add user"');
  print('');
  print('🎯 Alternative: Use the Firebase Registration Screen');
  print('1. Run your Flutter app: flutter run');
  print('2. Navigate to /debug-auth');
  print('3. Click "Register Firebase Account"');
  print('4. Use the form or quick test buttons');
  print('');
  print('💡 The account will be created in your Firebase project');
  print('💡 You can then use these credentials to sign in');
}
