// Mocks generated by Mockito 5.4.5 from annotations
// in myapp/test/widgets/unified_entry_form_edit_mode_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:myapp/models/entry.dart' as _i6;
import 'package:myapp/models/user_red_day.dart' as _i3;
import 'package:myapp/providers/entry_provider.dart' as _i5;
import 'package:myapp/repositories/user_red_day_repository.dart' as _i11;
import 'package:myapp/services/holiday_service.dart' as _i4;
import 'package:myapp/services/supabase_auth_service.dart' as _i10;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRedDay_1 extends _i1.SmartFake implements _i3.UserRedDay {
  _FakeUserRedDay_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRedDayInfo_2 extends _i1.SmartFake implements _i4.RedDayInfo {
  _FakeRedDayInfo_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EntryProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntryProvider extends _i1.Mock implements _i5.EntryProvider {
  MockEntryProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.Entry> get entries => (super.noSuchMethod(
        Invocation.getter(#entries),
        returnValue: <_i6.Entry>[],
      ) as List<_i6.Entry>);

  @override
  List<_i6.Entry> get filteredEntries => (super.noSuchMethod(
        Invocation.getter(#filteredEntries),
        returnValue: <_i6.Entry>[],
      ) as List<_i6.Entry>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> loadEntries() => (super.noSuchMethod(
        Invocation.method(
          #loadEntries,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addEntry(_i6.Entry? entry) => (super.noSuchMethod(
        Invocation.method(
          #addEntry,
          [entry],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addEntries(List<_i6.Entry>? entries) => (super.noSuchMethod(
        Invocation.method(
          #addEntries,
          [entries],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateEntry(_i6.Entry? entry) => (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteEntry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void filterEntries({
    String? searchQuery,
    _i6.EntryType? selectedType,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #filterEntries,
          [],
          {
            #searchQuery: searchQuery,
            #selectedType: selectedType,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFilters() => super.noSuchMethod(
        Invocation.method(
          #clearFilters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i6.Entry> getRecentEntries({int? limit = 10}) => (super.noSuchMethod(
        Invocation.method(
          #getRecentEntries,
          [],
          {#limit: limit},
        ),
        returnValue: <_i6.Entry>[],
      ) as List<_i6.Entry>);

  @override
  _i8.Future<void> clearDemoEntries() => (super.noSuchMethod(
        Invocation.method(
          #clearDemoEntries,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllEntries() => (super.noSuchMethod(
        Invocation.method(
          #clearAllEntries,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> syncLocalEntriesToSupabase() => (super.noSuchMethod(
        Invocation.method(
          #syncLocalEntriesToSupabase,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SupabaseAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseAuthService extends _i1.Mock
    implements _i10.SupabaseAuthService {
  MockSupabaseAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i2.AuthState> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i8.Stream<_i2.AuthState>.empty(),
      ) as _i8.Stream<_i2.AuthState>);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i2.AuthResponse> signIn(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
          ],
        ),
        returnValue: _i8.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #signIn,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i8.Future<_i2.AuthResponse>);

  @override
  _i8.Future<_i2.AuthResponse> signUp(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            email,
            password,
          ],
        ),
        returnValue: _i8.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #signUp,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i8.Future<_i2.AuthResponse>);

  @override
  _i8.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> sendPasswordResetEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> isAdmin() => (super.noSuchMethod(
        Invocation.method(
          #isAdmin,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> updateUserProfile({String? displayName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {#displayName: displayName},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> signOutWithCleanup(Function? cleanup) => (super.noSuchMethod(
        Invocation.method(
          #signOutWithCleanup,
          [cleanup],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> createAccountForDevelopment({
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccountForDevelopment,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HolidayService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHolidayService extends _i1.Mock implements _i4.HolidayService {
  MockHolidayService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get autoMarkHolidays => (super.noSuchMethod(
        Invocation.getter(#autoMarkHolidays),
        returnValue: false,
      ) as bool);

  @override
  String get countryCode => (super.noSuchMethod(
        Invocation.getter(#countryCode),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#countryCode),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void initialize({
    required _i11.UserRedDayRepository? repository,
    required String? userId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #repository: repository,
            #userId: userId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoMarkHolidays(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setAutoMarkHolidays,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> loadPersonalRedDays(int? year) => (super.noSuchMethod(
        Invocation.method(
          #loadPersonalRedDays,
          [year],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  List<_i3.UserRedDay> getPersonalRedDays(int? year) => (super.noSuchMethod(
        Invocation.method(
          #getPersonalRedDays,
          [year],
        ),
        returnValue: <_i3.UserRedDay>[],
      ) as List<_i3.UserRedDay>);

  @override
  _i3.UserRedDay? getPersonalRedDay(DateTime? date) =>
      (super.noSuchMethod(Invocation.method(
        #getPersonalRedDay,
        [date],
      )) as _i3.UserRedDay?);

  @override
  _i8.Future<_i3.UserRedDay> upsertPersonalRedDay(_i3.UserRedDay? redDay) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertPersonalRedDay,
          [redDay],
        ),
        returnValue: _i8.Future<_i3.UserRedDay>.value(_FakeUserRedDay_1(
          this,
          Invocation.method(
            #upsertPersonalRedDay,
            [redDay],
          ),
        )),
      ) as _i8.Future<_i3.UserRedDay>);

  @override
  _i8.Future<void> deletePersonalRedDay(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #deletePersonalRedDay,
          [date],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isHoliday(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #isHoliday,
          [date],
        ),
        returnValue: false,
      ) as bool);

  @override
  String? getHolidayName(DateTime? date) =>
      (super.noSuchMethod(Invocation.method(
        #getHolidayName,
        [date],
      )) as String?);

  @override
  Set<DateTime> holidaysForYear(int? year) => (super.noSuchMethod(
        Invocation.method(
          #holidaysForYear,
          [year],
        ),
        returnValue: <DateTime>{},
      ) as Set<DateTime>);

  @override
  _i4.RedDayInfo getRedDayInfo(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getRedDayInfo,
          [date],
        ),
        returnValue: _FakeRedDayInfo_2(
          this,
          Invocation.method(
            #getRedDayInfo,
            [date],
          ),
        ),
      ) as _i4.RedDayInfo);

  @override
  bool isRedDay(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #isRedDay,
          [date],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.HolidayInfo? getHolidayInfo(DateTime? date) =>
      (super.noSuchMethod(Invocation.method(
        #getHolidayInfo,
        [date],
      )) as _i4.HolidayInfo?);

  @override
  List<_i4.HolidayInfo> getHolidaysWithNamesForYear(int? year) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHolidaysWithNamesForYear,
          [year],
        ),
        returnValue: <_i4.HolidayInfo>[],
      ) as List<_i4.HolidayInfo>);

  @override
  String getHolidayTooltip(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getHolidayTooltip,
          [date],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getHolidayTooltip,
            [date],
          ),
        ),
      ) as String);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
