// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtIMsYRAAzyK1MUeJGZBQvOheIKwlO_U8',
    appId: '1:33702661507:web:8c9c43dbd4932abcd47ab6',
    messagingSenderId: '33702661507',
    projectId: 'kvik-time-2',
    authDomain: 'kvik-time-2.firebaseapp.com',
    storageBucket: 'kvik-time-2.firebasestorage.app',
    measurementId: 'G-PSFKBQDT9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJFcNNjvIF77zBscgZ7aefgpa0O6T9wKI',
    appId: '1:33702661507:android:89baa2cc34be33acd47ab6',
    messagingSenderId: '33702661507',
    projectId: 'kvik-time-2',
    storageBucket: 'kvik-time-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzl1ruJeJ2_Rg33oAmgZ82JstHuwb0RhA',
    appId: '1:33702661507:ios:91b4df7293088d3fd47ab6',
    messagingSenderId: '33702661507',
    projectId: 'kvik-time-2',
    storageBucket: 'kvik-time-2.firebasestorage.app',
    androidClientId: '33702661507-8t52798o05bin2lsvt0b2ruucemoe59a.apps.googleusercontent.com',
    iosBundleId: 'se.kviktime.app',
  );

}