// Mocks generated by Mockito 5.4.5 from annotations
// in myapp/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:hive/hive.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:myapp/models/user_profile.dart' as _i9;
import 'package:myapp/models/user_red_day.dart' as _i3;
import 'package:myapp/repositories/user_red_day_repository.dart' as _i12;
import 'package:myapp/services/holiday_service.dart' as _i4;
import 'package:myapp/services/profile_service.dart' as _i8;
import 'package:myapp/services/supabase_auth_service.dart' as _i5;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRedDay_1 extends _i1.SmartFake implements _i3.UserRedDay {
  _FakeUserRedDay_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRedDayInfo_2 extends _i1.SmartFake implements _i4.RedDayInfo {
  _FakeRedDayInfo_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SupabaseAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseAuthService extends _i1.Mock
    implements _i5.SupabaseAuthService {
  @override
  set onSessionExpired(dynamic Function()? _onSessionExpired) =>
      super.noSuchMethod(
        Invocation.setter(
          #onSessionExpired,
          _onSessionExpired,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<_i2.AuthState> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i6.Stream<_i2.AuthState>.empty(),
        returnValueForMissingStub: _i6.Stream<_i2.AuthState>.empty(),
      ) as _i6.Stream<_i2.AuthState>);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasValidSession => (super.noSuchMethod(
        Invocation.getter(#hasValidSession),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> refreshSession() => (super.noSuchMethod(
        Invocation.method(
          #refreshSession,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> ensureValidSession() => (super.noSuchMethod(
        Invocation.method(
          #ensureValidSession,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i2.AuthResponse> signIn(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #signIn,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #signIn,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i6.Future<_i2.AuthResponse>);

  @override
  _i6.Future<_i2.AuthResponse> signUp(
    String? email,
    String? password, {
    String? firstName,
    String? lastName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            email,
            password,
          ],
          {
            #firstName: firstName,
            #lastName: lastName,
          },
        ),
        returnValue: _i6.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #signUp,
            [
              email,
              password,
            ],
            {
              #firstName: firstName,
              #lastName: lastName,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #signUp,
            [
              email,
              password,
            ],
            {
              #firstName: firstName,
              #lastName: lastName,
            },
          ),
        )),
      ) as _i6.Future<_i2.AuthResponse>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> sendPasswordResetEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isAdmin() => (super.noSuchMethod(
        Invocation.method(
          #isAdmin,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> updateUserProfile({String? displayName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {#displayName: displayName},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signOutWithCleanup(Function? cleanup) => (super.noSuchMethod(
        Invocation.method(
          #signOutWithCleanup,
          [cleanup],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> createAccountForDevelopment({
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccountForDevelopment,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileService extends _i1.Mock implements _i8.ProfileService {
  @override
  _i6.Future<_i9.UserProfile?> fetchProfile() => (super.noSuchMethod(
        Invocation.method(
          #fetchProfile,
          [],
        ),
        returnValue: _i6.Future<_i9.UserProfile?>.value(),
        returnValueForMissingStub: _i6.Future<_i9.UserProfile?>.value(),
      ) as _i6.Future<_i9.UserProfile?>);

  @override
  _i6.Future<_i9.UserProfile?> acceptLegal() => (super.noSuchMethod(
        Invocation.method(
          #acceptLegal,
          [],
        ),
        returnValue: _i6.Future<_i9.UserProfile?>.value(),
        returnValueForMissingStub: _i6.Future<_i9.UserProfile?>.value(),
      ) as _i6.Future<_i9.UserProfile?>);

  @override
  _i6.Future<_i8.LegalVersions?> fetchCurrentLegalVersions() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCurrentLegalVersions,
          [],
        ),
        returnValue: _i6.Future<_i8.LegalVersions?>.value(),
        returnValueForMissingStub: _i6.Future<_i8.LegalVersions?>.value(),
      ) as _i6.Future<_i8.LegalVersions?>);

  @override
  _i6.Future<bool> profileExists() => (super.noSuchMethod(
        Invocation.method(
          #profileExists,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i9.UserProfile?> updateContractSettings({
    required int? contractPercent,
    required int? fullTimeHours,
    DateTime? trackingStartDate,
    required int? openingFlexMinutes,
    required String? employerMode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContractSettings,
          [],
          {
            #contractPercent: contractPercent,
            #fullTimeHours: fullTimeHours,
            #trackingStartDate: trackingStartDate,
            #openingFlexMinutes: openingFlexMinutes,
            #employerMode: employerMode,
          },
        ),
        returnValue: _i6.Future<_i9.UserProfile?>.value(),
        returnValueForMissingStub: _i6.Future<_i9.UserProfile?>.value(),
      ) as _i6.Future<_i9.UserProfile?>);

  @override
  _i6.Future<void> updateContractField(
    String? field,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContractField,
          [
            field,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [HolidayService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHolidayService extends _i1.Mock implements _i4.HolidayService {
  @override
  bool get autoMarkHolidays => (super.noSuchMethod(
        Invocation.getter(#autoMarkHolidays),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get countryCode => (super.noSuchMethod(
        Invocation.getter(#countryCode),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#countryCode),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.getter(#countryCode),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<void> initHive(_i11.Box<_i3.UserRedDay>? box) =>
      (super.noSuchMethod(
        Invocation.method(
          #initHive,
          [box],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void initialize({
    required _i12.UserRedDayRepository? repository,
    required String? userId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #repository: repository,
            #userId: userId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAutoMarkHolidays(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setAutoMarkHolidays,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> loadPersonalRedDays(int? year) => (super.noSuchMethod(
        Invocation.method(
          #loadPersonalRedDays,
          [year],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  List<_i3.UserRedDay> getPersonalRedDays(int? year) => (super.noSuchMethod(
        Invocation.method(
          #getPersonalRedDays,
          [year],
        ),
        returnValue: <_i3.UserRedDay>[],
        returnValueForMissingStub: <_i3.UserRedDay>[],
      ) as List<_i3.UserRedDay>);

  @override
  _i3.UserRedDay? getPersonalRedDay(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getPersonalRedDay,
          [date],
        ),
        returnValueForMissingStub: null,
      ) as _i3.UserRedDay?);

  @override
  _i6.Future<_i3.UserRedDay> upsertPersonalRedDay(_i3.UserRedDay? redDay) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertPersonalRedDay,
          [redDay],
        ),
        returnValue: _i6.Future<_i3.UserRedDay>.value(_FakeUserRedDay_1(
          this,
          Invocation.method(
            #upsertPersonalRedDay,
            [redDay],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.UserRedDay>.value(_FakeUserRedDay_1(
          this,
          Invocation.method(
            #upsertPersonalRedDay,
            [redDay],
          ),
        )),
      ) as _i6.Future<_i3.UserRedDay>);

  @override
  _i6.Future<void> deletePersonalRedDay(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #deletePersonalRedDay,
          [date],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool isHoliday(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #isHoliday,
          [date],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String? getHolidayName(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getHolidayName,
          [date],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  Set<DateTime> holidaysForYear(int? year) => (super.noSuchMethod(
        Invocation.method(
          #holidaysForYear,
          [year],
        ),
        returnValue: <DateTime>{},
        returnValueForMissingStub: <DateTime>{},
      ) as Set<DateTime>);

  @override
  _i4.RedDayInfo getRedDayInfo(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getRedDayInfo,
          [date],
        ),
        returnValue: _FakeRedDayInfo_2(
          this,
          Invocation.method(
            #getRedDayInfo,
            [date],
          ),
        ),
        returnValueForMissingStub: _FakeRedDayInfo_2(
          this,
          Invocation.method(
            #getRedDayInfo,
            [date],
          ),
        ),
      ) as _i4.RedDayInfo);

  @override
  bool isRedDay(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #isRedDay,
          [date],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.HolidayInfo? getHolidayInfo(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getHolidayInfo,
          [date],
        ),
        returnValueForMissingStub: null,
      ) as _i4.HolidayInfo?);

  @override
  List<_i4.HolidayInfo> getHolidaysWithNamesForYear(int? year) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHolidaysWithNamesForYear,
          [year],
        ),
        returnValue: <_i4.HolidayInfo>[],
        returnValueForMissingStub: <_i4.HolidayInfo>[],
      ) as List<_i4.HolidayInfo>);

  @override
  String getHolidayTooltip(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getHolidayTooltip,
          [date],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #getHolidayTooltip,
            [date],
          ),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #getHolidayTooltip,
            [date],
          ),
        ),
      ) as String);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
