// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkTfV_l8Um_66jRugu4KvaZhPXf8UeUT4',
    appId: '1:1011662335499:web:b1690b31c0d6840107610e',
    messagingSenderId: '1011662335499',
    projectId: 'kviktime-9ee5f',
    authDomain: 'kviktime-9ee5f.firebaseapp.com',
    storageBucket: 'kviktime-9ee5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkTfV_l8Um_66jRugu4KvaZhPXf8UeUT4',
    appId: '1:1011662335499:android:b1690b31c0d6840107610e',
    messagingSenderId: '1011662335499',
    projectId: 'kviktime-9ee5f',
    storageBucket: 'kviktime-9ee5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkTfV_l8Um_66jRugu4KvaZhPXf8UeUT4',
    appId: '1:1011662335499:ios:b1690b31c0d6840107610e',
    messagingSenderId: '1011662335499',
    projectId: 'kviktime-9ee5f',
    storageBucket: 'kviktime-9ee5f.firebasestorage.app',
    iosBundleId: 'se.kviktime.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkTfV_l8Um_66jRugu4KvaZhPXf8UeUT4',
    appId: '1:1011662335499:macos:b1690b31c0d6840107610e',
    messagingSenderId: '1011662335499',
    projectId: 'kviktime-9ee5f',
    storageBucket: 'kviktime-9ee5f.firebasestorage.app',
    iosBundleId: 'se.kviktime.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkTfV_l8Um_66jRugu4KvaZhPXf8UeUT4',
    appId: '1:1011662335499:windows:b1690b31c0d6840107610e',
    messagingSenderId: '1011662335499',
    projectId: 'kviktime-9ee5f',
    storageBucket: 'kviktime-9ee5f.firebasestorage.app',
  );
}
