// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2hoClGmnBzuOE5s3_ZVZAKsehTJq8So8',
    appId: '1:591378163668:web:2b6eff9623d72722b65841',
    messagingSenderId: '591378163668',
    projectId: 'time-app-8cd2d',
    authDomain: 'time-app-8cd2d.firebaseapp.com',
    storageBucket: 'time-app-8cd2d.firebasestorage.app',
    measurementId: 'G-WRHP0CSJKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPBtmWkR2L3bk-9-T5vdKOVuCpVaXXpgs',
    appId: '1:591378163668:android:7b17765c212ad1cab65841',
    messagingSenderId: '591378163668',
    projectId: 'time-app-8cd2d',
    storageBucket: 'time-app-8cd2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrRbyBvJDrEn8IQPlaBXa4MfeHneH9rAY',
    appId: '1:591378163668:ios:f76cbbbe2c6cf6e1b65841',
    messagingSenderId: '591378163668',
    projectId: 'time-app-8cd2d',
    storageBucket: 'time-app-8cd2d.firebasestorage.app',
    iosBundleId: 'se.kviltime.logger',
  );
}
