// Mocks generated by Mockito 5.4.5 from annotations
// in myapp/test/screens/unified_home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:ui' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:flutter/foundation.dart' as _i5;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:myapp/models/autocomplete_suggestion.dart' as _i20;
import 'package:myapp/models/entry.dart' as _i14;
import 'package:myapp/models/location.dart' as _i19;
import 'package:myapp/models/travel_entry.dart' as _i11;
import 'package:myapp/models/work_entry.dart' as _i12;
import 'package:myapp/providers/entry_provider.dart' as _i13;
import 'package:myapp/providers/location_provider.dart' as _i18;
import 'package:myapp/providers/theme_provider.dart' as _i21;
import 'package:myapp/repositories/contract_repository.dart' as _i8;
import 'package:myapp/repositories/leave_repository.dart' as _i9;
import 'package:myapp/repositories/location_repository.dart' as _i10;
import 'package:myapp/repositories/repository_provider.dart' as _i22;
import 'package:myapp/repositories/travel_repository.dart' as _i6;
import 'package:myapp/repositories/work_repository.dart' as _i7;
import 'package:myapp/services/auth_service.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColor_1 extends _i1.SmartFake implements _i3.Color {
  _FakeColor_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeData_2 extends _i1.SmartFake implements _i4.ThemeData {
  _FakeThemeData_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeUserMetadata_3 extends _i1.SmartFake implements _i2.UserMetadata {
  _FakeUserMetadata_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiFactor_4 extends _i1.SmartFake implements _i2.MultiFactor {
  _FakeMultiFactor_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIdTokenResult_5 extends _i1.SmartFake implements _i2.IdTokenResult {
  _FakeIdTokenResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfirmationResult_6 extends _i1.SmartFake
    implements _i2.ConfirmationResult {
  _FakeConfirmationResult_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_7 extends _i1.SmartFake implements _i2.User {
  _FakeUser_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTravelRepository_8 extends _i1.SmartFake
    implements _i6.TravelRepository {
  _FakeTravelRepository_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkRepository_9 extends _i1.SmartFake
    implements _i7.WorkRepository {
  _FakeWorkRepository_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContractRepository_10 extends _i1.SmartFake
    implements _i8.ContractRepository {
  _FakeContractRepository_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLeaveRepository_11 extends _i1.SmartFake
    implements _i9.LeaveRepository {
  _FakeLeaveRepository_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationRepository_12 extends _i1.SmartFake
    implements _i10.LocationRepository {
  _FakeLocationRepository_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTravelEntry_13 extends _i1.SmartFake implements _i11.TravelEntry {
  _FakeTravelEntry_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkEntry_14 extends _i1.SmartFake implements _i12.WorkEntry {
  _FakeWorkEntry_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EntryProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntryProvider extends _i1.Mock implements _i13.EntryProvider {
  MockEntryProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i14.Entry> get entries => (super.noSuchMethod(
        Invocation.getter(#entries),
        returnValue: <_i14.Entry>[],
      ) as List<_i14.Entry>);

  @override
  List<_i14.Entry> get filteredEntries => (super.noSuchMethod(
        Invocation.getter(#filteredEntries),
        returnValue: <_i14.Entry>[],
      ) as List<_i14.Entry>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i16.Future<void> loadEntries() => (super.noSuchMethod(
        Invocation.method(
          #loadEntries,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> addEntry(_i14.Entry? entry) => (super.noSuchMethod(
        Invocation.method(
          #addEntry,
          [entry],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> updateEntry(_i14.Entry? entry) => (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> deleteEntry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [id],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  void filterEntries({
    String? searchQuery,
    _i14.EntryType? selectedType,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #filterEntries,
          [],
          {
            #searchQuery: searchQuery,
            #selectedType: selectedType,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFilters() => super.noSuchMethod(
        Invocation.method(
          #clearFilters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i14.Entry> getRecentEntries({int? limit = 10}) => (super.noSuchMethod(
        Invocation.method(
          #getRecentEntries,
          [],
          {#limit: limit},
        ),
        returnValue: <_i14.Entry>[],
      ) as List<_i14.Entry>);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i17.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i16.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<_i2.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue:
            _i16.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #signInWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i16.Future<_i2.UserCredential>);

  @override
  _i16.Future<_i2.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue:
            _i16.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #createUserWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i16.Future<_i2.UserCredential>);

  @override
  _i16.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> sendPasswordResetEmail({required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [],
          {#email: email},
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<bool> isAdmin() => (super.noSuchMethod(
        Invocation.method(
          #isAdmin,
          [],
        ),
        returnValue: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);

  @override
  _i16.Future<void> updateUserProfile({String? displayName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {#displayName: displayName},
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<_i2.UserCredential> createAccountForDevelopment({
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccountForDevelopment,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue:
            _i16.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #createAccountForDevelopment,
            [],
            {
              #email: email,
              #password: password,
              #displayName: displayName,
            },
          ),
        )),
      ) as _i16.Future<_i2.UserCredential>);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationProvider extends _i1.Mock implements _i18.LocationProvider {
  MockLocationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i19.Location> get locations => (super.noSuchMethod(
        Invocation.getter(#locations),
        returnValue: <_i19.Location>[],
      ) as List<_i19.Location>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i16.Future<void> refreshLocations() => (super.noSuchMethod(
        Invocation.method(
          #refreshLocations,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> addLocation(_i19.Location? location) => (super.noSuchMethod(
        Invocation.method(
          #addLocation,
          [location],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> deleteLocation(_i19.Location? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [location],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> updateLocation(_i19.Location? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [location],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  List<_i19.Location> getLocationsByName(String? query) => (super.noSuchMethod(
        Invocation.method(
          #getLocationsByName,
          [query],
        ),
        returnValue: <_i19.Location>[],
      ) as List<_i19.Location>);

  @override
  List<_i19.Location> getFavoriteLocations() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteLocations,
          [],
        ),
        returnValue: <_i19.Location>[],
      ) as List<_i19.Location>);

  @override
  List<_i19.Location> getMostUsedLocations({int? limit = 5}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMostUsedLocations,
          [],
          {#limit: limit},
        ),
        returnValue: <_i19.Location>[],
      ) as List<_i19.Location>);

  @override
  List<_i19.Location> getRecentLocations({int? limit = 5}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentLocations,
          [],
          {#limit: limit},
        ),
        returnValue: <_i19.Location>[],
      ) as List<_i19.Location>);

  @override
  List<_i19.Location> searchLocations(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchLocations,
          [query],
        ),
        returnValue: <_i19.Location>[],
      ) as List<_i19.Location>);

  @override
  List<_i20.AutocompleteSuggestion> getAutocompleteSuggestions(
    String? query, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAutocompleteSuggestions,
          [query],
          {#limit: limit},
        ),
        returnValue: <_i20.AutocompleteSuggestion>[],
      ) as List<_i20.AutocompleteSuggestion>);

  @override
  List<String> getAddressSuggestions(
    String? query, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddressSuggestions,
          [query],
          {#limit: limit},
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<_i19.Location> getRecentlyAddedLocations({int? limit = 5}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentlyAddedLocations,
          [],
          {#limit: limit},
        ),
        returnValue: <_i19.Location>[],
      ) as List<_i19.Location>);

  @override
  _i16.Future<void> toggleFavorite(String? locationId) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [locationId],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> incrementUsageCount(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementUsageCount,
          [locationId],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i21.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i4.ThemeMode.system,
      ) as _i4.ThemeMode);

  @override
  _i3.Color get seedColor => (super.noSuchMethod(
        Invocation.getter(#seedColor),
        returnValue: _FakeColor_1(
          this,
          Invocation.getter(#seedColor),
        ),
      ) as _i3.Color);

  @override
  bool get useDynamicColor => (super.noSuchMethod(
        Invocation.getter(#useDynamicColor),
        returnValue: false,
      ) as bool);

  @override
  double get textScaleFactor => (super.noSuchMethod(
        Invocation.getter(#textScaleFactor),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isDarkMode => (super.noSuchMethod(
        Invocation.getter(#isDarkMode),
        returnValue: false,
      ) as bool);

  @override
  bool get isLightMode => (super.noSuchMethod(
        Invocation.getter(#isLightMode),
        returnValue: false,
      ) as bool);

  @override
  bool get isSystemMode => (super.noSuchMethod(
        Invocation.getter(#isSystemMode),
        returnValue: false,
      ) as bool);

  @override
  _i4.ThemeData get lightTheme => (super.noSuchMethod(
        Invocation.getter(#lightTheme),
        returnValue: _FakeThemeData_2(
          this,
          Invocation.getter(#lightTheme),
        ),
      ) as _i4.ThemeData);

  @override
  _i4.ThemeData get darkTheme => (super.noSuchMethod(
        Invocation.getter(#darkTheme),
        returnValue: _FakeThemeData_2(
          this,
          Invocation.getter(#darkTheme),
        ),
      ) as _i4.ThemeData);

  @override
  String get themeModeDisplayName => (super.noSuchMethod(
        Invocation.getter(#themeModeDisplayName),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#themeModeDisplayName),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void toggleTheme() => super.noSuchMethod(
        Invocation.method(
          #toggleTheme,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setThemeMode(_i4.ThemeMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSystemTheme() => super.noSuchMethod(
        Invocation.method(
          #setSystemTheme,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSeedColor(_i3.Color? color) => super.noSuchMethod(
        Invocation.method(
          #setSeedColor,
          [color],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleDynamicColor() => super.noSuchMethod(
        Invocation.method(
          #toggleDynamicColor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTextScaleFactor(double? factor) => super.noSuchMethod(
        Invocation.method(
          #setTextScaleFactor,
          [factor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetToDefaults() => super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getColorName(_i3.Color? color) => (super.noSuchMethod(
        Invocation.method(
          #getColorName,
          [color],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #getColorName,
            [color],
          ),
        ),
      ) as String);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i2.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified => (super.noSuchMethod(
        Invocation.getter(#emailVerified),
        returnValue: false,
      ) as bool);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
      ) as bool);

  @override
  _i2.UserMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeUserMetadata_3(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i2.UserMetadata);

  @override
  List<_i2.UserInfo> get providerData => (super.noSuchMethod(
        Invocation.getter(#providerData),
        returnValue: <_i2.UserInfo>[],
      ) as List<_i2.UserInfo>);

  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
      ) as String);

  @override
  _i2.MultiFactor get multiFactor => (super.noSuchMethod(
        Invocation.getter(#multiFactor),
        returnValue: _FakeMultiFactor_4(
          this,
          Invocation.getter(#multiFactor),
        ),
      ) as _i2.MultiFactor);

  @override
  _i16.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdToken,
          [forceRefresh],
        ),
        returnValue: _i16.Future<String?>.value(),
      ) as _i16.Future<String?>);

  @override
  _i16.Future<_i2.IdTokenResult> getIdTokenResult(
          [bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdTokenResult,
          [forceRefresh],
        ),
        returnValue: _i16.Future<_i2.IdTokenResult>.value(_FakeIdTokenResult_5(
          this,
          Invocation.method(
            #getIdTokenResult,
            [forceRefresh],
          ),
        )),
      ) as _i16.Future<_i2.IdTokenResult>);

  @override
  _i16.Future<_i2.UserCredential> linkWithCredential(
          _i2.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithCredential,
          [credential],
        ),
        returnValue:
            _i16.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #linkWithCredential,
            [credential],
          ),
        )),
      ) as _i16.Future<_i2.UserCredential>);

  @override
  _i16.Future<_i2.UserCredential> linkWithProvider(
          _i2.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithProvider,
          [provider],
        ),
        returnValue:
            _i16.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #linkWithProvider,
            [provider],
          ),
        )),
      ) as _i16.Future<_i2.UserCredential>);

  @override
  _i16.Future<_i2.UserCredential> reauthenticateWithProvider(
          _i2.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithProvider,
          [provider],
        ),
        returnValue:
            _i16.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #reauthenticateWithProvider,
            [provider],
          ),
        )),
      ) as _i16.Future<_i2.UserCredential>);

  @override
  _i16.Future<_i2.UserCredential> reauthenticateWithPopup(
          _i2.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithPopup,
          [provider],
        ),
        returnValue:
            _i16.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #reauthenticateWithPopup,
            [provider],
          ),
        )),
      ) as _i16.Future<_i2.UserCredential>);

  @override
  _i16.Future<void> reauthenticateWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithRedirect,
          [provider],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<_i2.UserCredential> linkWithPopup(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithPopup,
          [provider],
        ),
        returnValue:
            _i16.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #linkWithPopup,
            [provider],
          ),
        )),
      ) as _i16.Future<_i2.UserCredential>);

  @override
  _i16.Future<void> linkWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithRedirect,
          [provider],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<_i2.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i2.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithPhoneNumber,
          [
            phoneNumber,
            verifier,
          ],
        ),
        returnValue:
            _i16.Future<_i2.ConfirmationResult>.value(_FakeConfirmationResult_6(
          this,
          Invocation.method(
            #linkWithPhoneNumber,
            [
              phoneNumber,
              verifier,
            ],
          ),
        )),
      ) as _i16.Future<_i2.ConfirmationResult>);

  @override
  _i16.Future<_i2.UserCredential> reauthenticateWithCredential(
          _i2.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithCredential,
          [credential],
        ),
        returnValue:
            _i16.Future<_i2.UserCredential>.value(_FakeUserCredential_0(
          this,
          Invocation.method(
            #reauthenticateWithCredential,
            [credential],
          ),
        )),
      ) as _i16.Future<_i2.UserCredential>);

  @override
  _i16.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> sendEmailVerification(
          [_i2.ActionCodeSettings? actionCodeSettings]) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [actionCodeSettings],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<_i2.User> unlink(String? providerId) => (super.noSuchMethod(
        Invocation.method(
          #unlink,
          [providerId],
        ),
        returnValue: _i16.Future<_i2.User>.value(_FakeUser_7(
          this,
          Invocation.method(
            #unlink,
            [providerId],
          ),
        )),
      ) as _i16.Future<_i2.User>);

  @override
  _i16.Future<void> updateEmail(String? newEmail) => (super.noSuchMethod(
        Invocation.method(
          #updateEmail,
          [newEmail],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> updatePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [newPassword],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> updatePhoneNumber(
          _i2.PhoneAuthCredential? phoneCredential) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhoneNumber,
          [phoneCredential],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [displayName],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> updatePhotoURL(String? photoURL) => (super.noSuchMethod(
        Invocation.method(
          #updatePhotoURL,
          [photoURL],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> updateProfile({
    String? displayName,
    String? photoURL,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #displayName: displayName,
            #photoURL: photoURL,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i2.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyBeforeUpdateEmail,
          [
            newEmail,
            actionCodeSettings,
          ],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
}

/// A class which mocks [RepositoryProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepositoryProvider extends _i1.Mock
    implements _i22.RepositoryProvider {
  MockRepositoryProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TravelRepository get travelRepository => (super.noSuchMethod(
        Invocation.getter(#travelRepository),
        returnValue: _FakeTravelRepository_8(
          this,
          Invocation.getter(#travelRepository),
        ),
      ) as _i6.TravelRepository);

  @override
  set travelRepository(_i6.TravelRepository? _travelRepository) =>
      super.noSuchMethod(
        Invocation.setter(
          #travelRepository,
          _travelRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.WorkRepository get workRepository => (super.noSuchMethod(
        Invocation.getter(#workRepository),
        returnValue: _FakeWorkRepository_9(
          this,
          Invocation.getter(#workRepository),
        ),
      ) as _i7.WorkRepository);

  @override
  set workRepository(_i7.WorkRepository? _workRepository) => super.noSuchMethod(
        Invocation.setter(
          #workRepository,
          _workRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.ContractRepository get contractRepository => (super.noSuchMethod(
        Invocation.getter(#contractRepository),
        returnValue: _FakeContractRepository_10(
          this,
          Invocation.getter(#contractRepository),
        ),
      ) as _i8.ContractRepository);

  @override
  set contractRepository(_i8.ContractRepository? _contractRepository) =>
      super.noSuchMethod(
        Invocation.setter(
          #contractRepository,
          _contractRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.LeaveRepository get leaveRepository => (super.noSuchMethod(
        Invocation.getter(#leaveRepository),
        returnValue: _FakeLeaveRepository_11(
          this,
          Invocation.getter(#leaveRepository),
        ),
      ) as _i9.LeaveRepository);

  @override
  set leaveRepository(_i9.LeaveRepository? _leaveRepository) =>
      super.noSuchMethod(
        Invocation.setter(
          #leaveRepository,
          _leaveRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.LocationRepository get locationRepository => (super.noSuchMethod(
        Invocation.getter(#locationRepository),
        returnValue: _FakeLocationRepository_12(
          this,
          Invocation.getter(#locationRepository),
        ),
      ) as _i10.LocationRepository);

  @override
  set locationRepository(_i10.LocationRepository? _locationRepository) =>
      super.noSuchMethod(
        Invocation.setter(
          #locationRepository,
          _locationRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
}

/// A class which mocks [TravelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTravelRepository extends _i1.Mock implements _i6.TravelRepository {
  MockTravelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i11.TravelEntry> getAllForUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getAllForUser,
          [userId],
        ),
        returnValue: <_i11.TravelEntry>[],
      ) as List<_i11.TravelEntry>);

  @override
  List<_i11.TravelEntry> getForUserInRange(
    String? userId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForUserInRange,
          [
            userId,
            start,
            end,
          ],
        ),
        returnValue: <_i11.TravelEntry>[],
      ) as List<_i11.TravelEntry>);

  @override
  _i16.Future<_i11.TravelEntry> add(_i11.TravelEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [entry],
        ),
        returnValue: _i16.Future<_i11.TravelEntry>.value(_FakeTravelEntry_13(
          this,
          Invocation.method(
            #add,
            [entry],
          ),
        )),
      ) as _i16.Future<_i11.TravelEntry>);

  @override
  _i16.Future<_i11.TravelEntry> update(_i11.TravelEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [entry],
        ),
        returnValue: _i16.Future<_i11.TravelEntry>.value(_FakeTravelEntry_13(
          this,
          Invocation.method(
            #update,
            [entry],
          ),
        )),
      ) as _i16.Future<_i11.TravelEntry>);

  @override
  _i16.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  int getTotalMinutesInRange(
    String? userId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalMinutesInRange,
          [
            userId,
            start,
            end,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i16.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
}

/// A class which mocks [WorkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkRepository extends _i1.Mock implements _i7.WorkRepository {
  MockWorkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i12.WorkEntry> getAllForUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getAllForUser,
          [userId],
        ),
        returnValue: <_i12.WorkEntry>[],
      ) as List<_i12.WorkEntry>);

  @override
  List<_i12.WorkEntry> getForUserInRange(
    String? userId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForUserInRange,
          [
            userId,
            start,
            end,
          ],
        ),
        returnValue: <_i12.WorkEntry>[],
      ) as List<_i12.WorkEntry>);

  @override
  _i16.Future<_i12.WorkEntry> add(_i12.WorkEntry? entry) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [entry],
        ),
        returnValue: _i16.Future<_i12.WorkEntry>.value(_FakeWorkEntry_14(
          this,
          Invocation.method(
            #add,
            [entry],
          ),
        )),
      ) as _i16.Future<_i12.WorkEntry>);

  @override
  _i16.Future<_i12.WorkEntry> update(_i12.WorkEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [entry],
        ),
        returnValue: _i16.Future<_i12.WorkEntry>.value(_FakeWorkEntry_14(
          this,
          Invocation.method(
            #update,
            [entry],
          ),
        )),
      ) as _i16.Future<_i12.WorkEntry>);

  @override
  _i16.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  int getTotalMinutesInRange(
    String? userId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalMinutesInRange,
          [
            userId,
            start,
            end,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i16.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
}
