// Mocks generated by Mockito 5.4.5 from annotations
// in myapp/test/screens/edit_entry_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:myapp/models/entry.dart' as _i4;
import 'package:myapp/providers/entry_provider.dart' as _i3;
import 'package:myapp/services/sync_queue_service.dart' as _i2;
import 'package:myapp/services/travel_cache_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EntryProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntryProvider extends _i1.Mock implements _i3.EntryProvider {
  MockEntryProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.Entry> get entries => (super.noSuchMethod(
        Invocation.getter(#entries),
        returnValue: <_i4.Entry>[],
      ) as List<_i4.Entry>);

  @override
  List<_i4.Entry> get filteredEntries => (super.noSuchMethod(
        Invocation.getter(#filteredEntries),
        returnValue: <_i4.Entry>[],
      ) as List<_i4.Entry>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isSyncing => (super.noSuchMethod(
        Invocation.getter(#isSyncing),
        returnValue: false,
      ) as bool);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  int get pendingOfflineOperations => (super.noSuchMethod(
        Invocation.getter(#pendingOfflineOperations),
        returnValue: 0,
      ) as int);

  @override
  bool get hasPendingSync => (super.noSuchMethod(
        Invocation.getter(#hasPendingSync),
        returnValue: false,
      ) as bool);

  @override
  int get pendingSyncCount => (super.noSuchMethod(
        Invocation.getter(#pendingSyncCount),
        returnValue: 0,
      ) as int);

  @override
  bool get isSyncInProgress => (super.noSuchMethod(
        Invocation.getter(#isSyncInProgress),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> handleAuthUserChanged({
    required String? previousUserId,
    required String? currentUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleAuthUserChanged,
          [],
          {
            #previousUserId: previousUserId,
            #currentUserId: currentUserId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadEntries() => (super.noSuchMethod(
        Invocation.method(
          #loadEntries,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addEntry(_i4.Entry? entry) => (super.noSuchMethod(
        Invocation.method(
          #addEntry,
          [entry],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addEntries(List<_i4.Entry>? entries) => (super.noSuchMethod(
        Invocation.method(
          #addEntries,
          [entries],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateEntry(
    _i4.Entry? entry, {
    _i3.ConflictStrategy? conflictStrategy = _i3.ConflictStrategy.newerWins,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
          {#conflictStrategy: conflictStrategy},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteEntry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void filterEntries({
    String? searchQuery,
    _i4.EntryType? selectedType,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #filterEntries,
          [],
          {
            #searchQuery: searchQuery,
            #selectedType: selectedType,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFilters() => super.noSuchMethod(
        Invocation.method(
          #clearFilters,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i4.Entry> getRecentEntries({int? limit = 10}) => (super.noSuchMethod(
        Invocation.method(
          #getRecentEntries,
          [],
          {#limit: limit},
        ),
        returnValue: <_i4.Entry>[],
      ) as List<_i4.Entry>);

  @override
  _i6.Future<void> clearDemoEntries() => (super.noSuchMethod(
        Invocation.method(
          #clearDemoEntries,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllEntries() => (super.noSuchMethod(
        Invocation.method(
          #clearAllEntries,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncLocalEntriesToSupabase() => (super.noSuchMethod(
        Invocation.method(
          #syncLocalEntriesToSupabase,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.SyncResult> processPendingSync() => (super.noSuchMethod(
        Invocation.method(
          #processPendingSync,
          [],
        ),
        returnValue: _i6.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #processPendingSync,
            [],
          ),
        )),
      ) as _i6.Future<_i2.SyncResult>);

  @override
  void clearSyncError() => super.noSuchMethod(
        Invocation.method(
          #clearSyncError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TravelCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTravelCacheService extends _i1.Mock
    implements _i8.TravelCacheService {
  MockTravelCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i8.CachedRoute? getCachedRoute({
    String? fromPlaceId,
    String? toPlaceId,
    String? fromText,
    String? toText,
    String? mode = 'driving',
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedRoute,
        [],
        {
          #fromPlaceId: fromPlaceId,
          #toPlaceId: toPlaceId,
          #fromText: fromText,
          #toText: toText,
          #mode: mode,
        },
      )) as _i8.CachedRoute?);

  @override
  _i6.Future<void> saveRoute({
    required String? from,
    required String? to,
    required int? minutes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRoute,
          [],
          {
            #from: from,
            #to: to,
            #minutes: minutes,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveRouteNamed({
    String? fromPlaceId,
    String? toPlaceId,
    String? fromText,
    String? toText,
    required int? minutes,
    double? distanceKm,
    String? mode = 'driving',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRouteNamed,
          [],
          {
            #fromPlaceId: fromPlaceId,
            #toPlaceId: toPlaceId,
            #fromText: fromText,
            #toText: toText,
            #minutes: minutes,
            #distanceKm: distanceKm,
            #mode: mode,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  int? getMinutes(
    String? from,
    String? to,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getMinutes,
        [
          from,
          to,
        ],
      )) as int?);

  @override
  int? getRouteDuration(
    String? from,
    String? to,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getRouteDuration,
        [
          from,
          to,
        ],
      )) as int?);

  @override
  _i6.Future<void> saveRouteLegacy(
    String? from,
    String? to,
    int? minutes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRouteLegacy,
          [
            from,
            to,
            minutes,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
