// Mocks generated by Mockito 5.4.5 from annotations
// in myapp/test/viewmodels/customer_analytics_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myapp/features/reports/analytics_models.dart' as _i2;
import 'package:myapp/services/analytics_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeServerAnalytics_0 extends _i1.SmartFake
    implements _i2.ServerAnalytics {
  _FakeServerAnalytics_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AnalyticsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsApi extends _i1.Mock implements _i3.AnalyticsApi {
  MockAnalyticsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ServerAnalytics> fetchDashboard({
    DateTime? startDate,
    DateTime? endDate,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDashboard,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #userId: userId,
          },
        ),
        returnValue:
            _i4.Future<_i2.ServerAnalytics>.value(_FakeServerAnalytics_0(
          this,
          Invocation.method(
            #fetchDashboard,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.ServerAnalytics>);
}
